export const TICTACTOE_USER_MARKED = 'TICTACTOE_USER_MARKED';
export const TICTACTOE_SERVER_MARKED = 'TICTACTOE_SERVER_MARKED';
export const TICTACTOE_REPLAY = 'TICTACTOE_REPLAY';
export const TICTACTOE_GAME_ON = 'TICTACTOE_GAME_ON';
export const TICTACTOE_USER_ACCEPT_DEFEAT = "TICTACTOE_USER_ACCEPT_DEFEAT";
export const TICTACTOE_IS_COMPLETE = "TICTACTOE_IS_COMPLETE";