export const TICTACTOE_USER_MARKED = 'TICTACTOE_USER_MARKED';
export const TICTACTOE_SERVER_MARKED = 'TICTACTOE_SERVER_MARKED';
export const TICTACTOE_REPLAY = 'TICTACTOE_REPLAY';
export const TICTACTOE_GAME_ON = 'TICTACTOE_GAME_ON';
export const TICTACTOE_USER_ACCEPT_DEFEAT = "TICTACTOE_USER_ACCEPT_DEFEAT";
export const TICTACTOE_IS_COMPLETE = "TICTACTOE_IS_COMPLETE";

export const SUDOKU_USER_CLICKED = "SUDOKU_USER_CLICKED";
export const SUDOKU_USER_MARKED  = "SUDOKU_USER_MARKED";
export const SUDOKU_USER_GAVEUP  = "SUDOKU_USER_GAVEUP";
export const SUDOKU_USER_REQUEST = "SUDOKU_USER_REQUEST";
export const SUDOKU_USER_RESET   = "SUDOKU_USER_RESET";
export const SUDOKU_WRONG_CHECK  = "SUDOKU_WRONG_CHECK";
export const SUDOKU_USER_ERASE   = "SUDOKU_USER_ERASE";